// examples/neon-website-waku/src/pages/index.tsx
import { getEnv } from "waku";
import { Card } from "../components/Card.tsx";
import { Counter } from "../components/Counter.tsx";

export default async function HomePage() {
  // `getEnv` reads the server environment at request time — the portable
  // way to reach env values from RSC page modules. On Neon it is backed by
  // the Neon Functions runtime's `process.env`.
  const greeting = getEnv("GREETING") ?? "Hello!";
  return (
    <div>
      <h1 className="text-3xl font-bold">{greeting}</h1>
      <Card
        title="Styled with Tailwind CSS"
        body="This card is a React component styled with Tailwind utilities."
      />
      <p className="mt-4 text-slate-600">This page is rendered by the server on every request.</p>
      <Counter />
    </div>
  );
}

// Dynamic: rendered by the Neon Functions runtime at request time.
export const getConfig = async () => ({ render: "dynamic" }) as const;

// examples/cloudflare-website-nuxt/app/pages/index.vue
<script setup lang="ts">
useHead({ title: "Nuxt on Cloudflare" });

// SSR reads the Worker environment through nitro's cloudflare_module
// runtime contract: `event.context.cloudflare.env`. `useState` serializes
// the server-read value into the payload so the client render matches.
const greeting = useState("greeting", () => {
  if (import.meta.server) {
    const event = useRequestEvent();
    const env = event?.context.cloudflare?.env as Record<string, unknown> | undefined;
    return typeof env?.GREETING === "string" ? env.GREETING : "Hello!";
  }
  return "Hello!";
});
</script>

<template>
  <main>
    <h1 class="text-3xl font-bold">{{ greeting }}</h1>
    <Card
      title="Styled with Tailwind CSS"
      body="This card is a Vue component styled with Tailwind utilities."
    />
    <NuxtLink class="mt-4 inline-block underline" to="/about">about (prerendered)</NuxtLink>
  </main>
</template>
